vich_uploader:
    db_driver: orm

    mappings:

        courses:
            uri_prefix: /images/courses
            upload_destination: '%kernel.project_dir%/assets/images/courses'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        pdf:
            uri_prefix: /images/programs
            upload_destination: '%kernel.project_dir%/assets/images/programs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        users:
            uri_prefix: /images/avatar
            upload_destination: '%kernel.project_dir%/assets/images/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        actus :
            uri_prefix: /images/actus
            upload_destination: '%kernel.project_dir%/assets/images/actus'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer